Repository Checkmarx/ast-cli, pull requests merged in 2022-07, with the labels that each got.

#423 Increase retry timeout flag default value
  internal/params/flags.go
  test/integration/auth_test.go
  test/integration/scan_test.go
Labels: enhancement, feature

#424 KICS Check different return codes
  internal/commands/scan.go
  internal/commands/scan_test.go
  test/integration/scan_test.go
Labels: bug

#426 Added new flag for kics platforms.
  internal/commands/scan.go
  internal/params/flags.go
Labels: feature

#427 Adding utils remediation sca command
  internal/commands/data/package.json
  internal/commands/scan.go
  internal/commands/util/remediation.go
  internal/commands/util/remediation_test.go
  internal/commands/util/utils.go
  internal/params/flags.go
  internal/wrappers/remediation/package-remediation-npm.go
  internal/wrappers/remediation/package-remediation.go
  test/integration/data/package.json
  test/integration/scan_test.go
  test/integration/util_remediation_test.go
Labels: feature

#430 adding kics remediation command under utils
  internal/commands/cx_result_sonar.json
  internal/commands/data/package.json
  internal/commands/data/positive1.tf
  internal/commands/data/results.json
  internal/commands/result.go
  internal/commands/util/remediation.go
  internal/commands/util/remediation_test.go
  internal/params/flags.go
  internal/wrappers/scan-kics-realtime.go
  test/integration/data/positive1.tf
  test/integration/data/results.json
  test/integration/scan_test.go
  test/integration/util_remediation_test.go
Labels: feature
