Repository Checkmarx/ast-cli, pull requests merged in 2022-06, with the labels that each got.

#408 GOARCH variable for windows should be amd64
  README.md
Labels: documentation, community

#414 Bug/change mac build to fat
  .goreleaser.yml
  gonArm.hcl
  gonMac.hcl
Labels: bug

#416 added auto release notes and teams notification with release details
  .github/workflows/release.yml
  internal/commands/scan.go
  test/integration/scan_test.go
Labels: feature

#417 adding teams notifications
  .github/release.yml
  .github/workflows/release.yml
  .goreleaser.yml
Labels: feature
