Repository Checkmarx/ast-cli, pull requests merged in 2024-08, with the labels that each got.

#644 Add Critical Severity - AST 21466
  internal/commands/predicates.go
  internal/commands/result.go
  internal/commands/result_test.go
  internal/commands/root.go
  internal/wrappers/feature-flags.go
  internal/wrappers/results-summary.go
  test/integration/pr_test.go
  test/integration/root_test.go
Labels: feature

#817 Adding critical severity on SCS table
  internal/commands/result.go
  internal/commands/result_test.go
  internal/wrappers/mock/scan-overview-mock.go
  internal/wrappers/results-summary.go
Labels: bug

#820 supporting api-sec missing case
  internal/commands/result.go
Labels: bug

#811 Threshold calculate API-security vulnerabilities (AST-45598)
  internal/commands/scan.go
  test/integration/scan_test.go
Labels: bug

#818 Revert test coverage to 80% (AST-46689)
  .github/workflows/ci.yml
  internal/commands/scan.go
  test/integration/scan_test.go
Labels: feature

#833 Display the description result incorrectly if the vulnerability contains quotation (AST-40454)
  internal/commands/result.go
  internal/commands/result_test.go
Labels: bug

#839 CLI | Fix TotalIssues=-1 when SCS FF is off (AST-63998)
  internal/commands/result.go
  internal/commands/result_test.go
Labels: bug, fix

#845 Add snooze or mute check for sca vulnerabilities
  internal/commands/result.go
  internal/wrappers/export.go
  internal/wrappers/results-sca-package.go
Labels: bug, fix

#842 Fix GitLab dashboard, Dependency Scanning 0 vulnerabilities error. (AST-63985)
  internal/commands/result.go
  test/integration/scan_test.go
Labels: bug

#847 CLI | Fix export service call param and update vulnerability identifier (AST-65461)
  go.mod
  go.sum
  internal/commands/result.go
  internal/services/export.go
  internal/wrappers/export.go
  internal/wrappers/results-sca-package.go
Labels: bug, fix

#852 CLI | Support download and execute of Vorpal engine in MacOS arm64 (AST-63697)
  internal/commands/vorpal/vorpalconfig/vorpal-mac-amd.go
  internal/commands/vorpal/vorpalconfig/vorpal-mac-arm.go
Labels: bug, fix
