Repository Checkmarx/ast-cli, pull requests merged in 2024-04, with the labels that each got.

#691 CLI | Add Missing PackageManager Types (AST-38138)
  internal/commands/scarealtime/sca-realtime-utils.go
  internal/commands/scarealtime/sca-realtime.go
  internal/commands/scarealtime/sca-realtime_test.go
Labels: bug

#693 CLI | Fast Scan configuration in SAST scanner (AST-37706)
  internal/commands/scan.go
  internal/commands/scan_test.go
  internal/params/flags.go
  internal/wrappers/scans.go
  test/integration/scan_test.go
Labels: feature

#695 CLI | Handling disabled repos in ADO
  internal/commands/util/usercount/azure.go
  internal/commands/util/usercount/user-count_test.go
  internal/params/flags.go
  internal/wrappers/azure-http.go
  internal/wrappers/azure.go
  internal/wrappers/mock/azure-mock.go
Labels: bug

#688 AST-36384 add support for improved-scan-report invocation
  .github/workflows/ci.yml
  go.mod
  go.sum
  internal/commands/cx_result_sonar.json
  internal/commands/result.go
  internal/commands/result_test.go
  internal/commands/scan.go
  internal/wrappers/feature-flags.go
  test/integration/result_test.go
  test/integration/scan_test.go
Labels: feature

#698 CLI | Add redirected request mechanism (AST-37864)
  internal/wrappers/client.go
Labels: bug

#690 Map CLI exit codes by scanner type (AST-37829)
  internal/commands/scan.go
  internal/commands/scan_test.go
  internal/commands/util/learnmore.go
  internal/errors/exit-codes/exit-codes.go
  internal/wrappers/mock/projects-mock.go
  internal/wrappers/mock/sca-realtime-mock.go
  internal/wrappers/mock/scans-mock.go
  test/integration/learnmore_test.go
  test/integration/scan_test.go
  test/integration/tenant_test.go
Labels: feature

#712 CLI | Add redirected request mechanism (AST-37864)
  go.mod
  internal/errors/application-errors.go
  internal/wrappers/client.go
Labels: bug

#714 Project Application association Issue - Workaround - AST-40286
  go.sum
  internal/commands/groups.go
  internal/commands/project.go
  internal/commands/scan.go
  internal/commands/scan_test.go
Labels: bug, community
