Repository Checkmarx/ast-cli, pull requests merged in 2024-12, with the labels that each got.

#951 Change IsAllowedEngine func to return true when packageEnforcementEnabled is false (AST-76112)
  .github/workflows/pr-linter.yml
  CODEOWNERS
  internal/services/asca_test.go
  internal/wrappers/jwt-helper.go
  test/integration/bfl_test.go
Labels: bug, fix

#954 Support for jsx files (AST-70294)
  internal/params/filters.go
Labels: bug

#968 CLI | Fix Primary branch deletion in CxOne (AST-74968)
  internal/services/projects.go
  internal/services/projects_test.go
Labels: bug

#957 CLI | Fix config retrieval logic (AST-76622)
  Dockerfile
  go.mod
  go.sum
  internal/commands/scan.go
  internal/commands/scan_test.go
  internal/wrappers/mock/scans-mock.go
  test/integration/scan_test.go
Labels: bug

#953 Do Not Update An Existing Project With A New Application(AST-70427)
  internal/commands/project.go
  internal/commands/scan.go
  internal/commands/scan_test.go
  internal/commands/util/import.go
  internal/services/applications.go
  internal/services/projects.go
  internal/services/projects_test.go
  internal/wrappers/mock/application-mock.go
  internal/wrappers/mock/constants.go
  test/integration/scan_test.go
Labels: bug

#977 CLI | Increase page limit to 10,000 in results service requests (AST-77955)
  go.mod
  go.sum
  internal/wrappers/results-http.go
Labels: bug

#973 Project list command filtered by tag with empty values - project without tag (AST-48293)
  internal/commands/project.go
  internal/commands/project_test.go
  internal/params/flags.go
  test/integration/project_test.go
Labels: feature

#980 Fix handle corrupted repos In BitBucket utils contributor-count (AST-76750)
  internal/commands/util/usercount/bitbucketserver/bitbucket-server.go
  internal/commands/util/usercount/bitbucketserver/bitbucket-server_test.go
  internal/wrappers/mock/bitbucketServer-mock.go
Labels: bug

#984 Ensure proper cleanup of temporary ZIP files (AST-42950)
  internal/commands/scan.go
Labels: bug, fix
