Repository Checkmarx/ast-cli, pull requests merged in 2024-09, with the labels that each got.

#854 CLI | Support download and execute of Vorpal engine in Linux arm64 (AST-63697)
  internal/commands/vorpal/vorpalconfig/vorpal-linux-amd.go
  internal/commands/vorpal/vorpalconfig/vorpal-linux-arm.go
Labels: bug, fix

#858 Removed BOM prefix from response body of export service (AST-66827)
  internal/wrappers/export-http.go
Labels: bug, fix

#853 Support SCS Vulnerabilities in json report when Agent is VSCode/AST-CLI (AST-63907) #850
  .github/workflows/ci.yml
  .github/workflows/manual-integration-test.yml
  internal/commands/result.go
  internal/commands/result_test.go
  internal/params/flags.go
  internal/wrappers/mock/results-mock.go
Labels: feature

#878 CLI | Fix SCS Engine Name
  internal/commands/result.go
Labels: bug, fix

#877 Implement Container Signing for Docker Images (AST-51994)
  .github/workflows/release.yml
  .goreleaser.yml
Labels: feature

#881 CLI | Upgrade setup docker on macos github action (AST-68752)
  .github/workflows/release.yml
Labels: bug, fix

#879 Print policy violations only if any rule was violated (AST-66024)
  go.mod
  go.sum
  internal/commands/result.go
  internal/commands/result_test.go
  internal/commands/util/pr.go
  internal/commands/util/pr_test.go
Labels: feature

#885 Integrate cosign for Docker image signature verification
  .github/workflows/release.yml
Labels: feature

#889 Update container signing Docker image (AST-51994)
  .github/workflows/release.yml
  .goreleaser.yml
  Dockerfile
Labels: feature

#880 PR linter (AST-37686)
  .github/workflows/pr-linter.yml
Labels: feature

#888 Dockerfile for Checkmarx CLI with FIPS (AST-66846)
  Dockerfile
Labels: feature

#890 Change to secrets from ENV (AST-51994)
  .goreleaser.yml
Labels: feature

#897 Support Comma In Project Name
  internal/services/projects.go
  internal/wrappers/mock/projects-mock.go
Labels: bug

#899 Sign docker image (AST-51994)
  .github/workflows/release.yml
  .goreleaser.yml
Labels: feature

#898 CLI | Add sca-hide-dev-test-dependencies Flag (AST-68368)
  go.mod
  go.sum
  internal/commands/result.go
  internal/commands/scan.go
  internal/params/flags.go
  internal/services/export.go
  test/integration/result_test.go
  test/integration/scan_test.go
Labels: feature
