Repository Checkmarx/ast-cli, pull requests merged in 2024-02, with the labels that each got.

#651 Initialize sarif arrays
  internal/commands/result.go
Labels: bug

#655 AST-35649 | fix ast-cli vulnerabilities
  .github/workflows/ci.yml
  .github/workflows/dependabot-auto-merge.yml
  .github/workflows/jira_notify.yml
  .github/workflows/nightly.yml
  .github/workflows/pr-label.yml
  .github/workflows/release.yml
  Dockerfile
  internal/commands/sast-prompt.go
  internal/commands/scan.go
  internal/commands/scarealtime/sca-realtime.go
  internal/commands/util/remediation.go
  test/integration/data/positive1.tf
Labels: bug

#660 Update release.yml
  .github/workflows/release.yml
Labels: bug, fix

#661 remove sca optin from scan log description
  internal/commands/scan.go
Labels: bug

#654 Encode client ID and secret
  internal/wrappers/client.go
Labels: bug

#643 Add policy violation to PR/MR decoration
  .golangci.yml
  internal/commands/policymanagement/policy.go
  internal/commands/result.go
  internal/commands/root.go
  internal/commands/scan.go
  internal/commands/util/pr.go
  internal/commands/util/pr_test.go
  internal/commands/util/utils.go
  internal/commands/util/utils_test.go
  internal/wrappers/mock/policy-mock.go
  internal/wrappers/policy.go
  internal/wrappers/pr.go
  internal/wrappers/results-summary.go
Labels: feature

#663 AST-35640 | Create Groups Assignment
  cmd/main.go
  internal/commands/groups.go
  internal/commands/groups_test.go
  internal/commands/project.go
  internal/commands/root.go
  internal/commands/root_test.go
  internal/commands/scan.go
  internal/commands/scan_test.go
  internal/params/binds.go
  internal/params/envs.go
  internal/params/keys.go
  internal/wrappers/access-management-http.go
  internal/wrappers/access-management.go
  internal/wrappers/feature-flags.go
  internal/wrappers/mock/access-management-mock.go
  internal/wrappers/mock/feature-flags-mock.go
  internal/wrappers/mock/groups-mock.go
  test/integration/project_test.go
  test/integration/root_test.go
  test/integration/scan_test.go
  test/integration/util.go
  test/integration/util_command.go
Labels: feature

#664 CLI | Support the application-name flag and add association to the project (AST-35636 , AST-35637)
  cmd/main.go
  internal/commands/project.go
  internal/commands/project_test.go
  internal/commands/root.go
  internal/commands/root_test.go
  internal/commands/scan.go
  internal/commands/scan_test.go
  internal/errors/application-errors.go
  internal/params/binds.go
  internal/params/envs.go
  internal/params/flags.go
  internal/params/keys.go
  internal/wrappers/application-http.go
  internal/wrappers/application.go
  internal/wrappers/azure-http.go
  internal/wrappers/bfl-http.go
  internal/wrappers/bitbucket-http.go
  internal/wrappers/codebashing-http.go
  internal/wrappers/feature-flags-http.go
  internal/wrappers/github-http.go
  internal/wrappers/gitlab-http.go
  internal/wrappers/groups-http.go
  internal/wrappers/mock/application-mock.go
  internal/wrappers/mock/constants.go
  internal/wrappers/mock/projects-mock.go
  internal/wrappers/pr-http.go
  internal/wrappers/predicates-http.go
  internal/wrappers/projects-http.go
  internal/wrappers/projects.go
  internal/wrappers/response.go
  internal/wrappers/results-http.go
  internal/wrappers/risks-overview-http.go
  internal/wrappers/sast-metadata-http.go
  internal/wrappers/scans-http.go
  internal/wrappers/wrapper-constants.go
  test/integration/project_test.go
  test/integration/scan_test.go
  test/integration/util_command.go
Labels: feature
