Repository Checkmarx/ast-cli, pull requests merged in 2024-06, with the labels that each got.

#744 CLI | Implementing Vorpal Wrapper Functionality (AST-42346)
  go.mod
  go.sum
  internal/services/vorpal.go
  internal/wrappers/grpcs/client.go
  internal/wrappers/grpcs/protos/vorpal/managements/management.pb.go
  internal/wrappers/grpcs/protos/vorpal/managements/management.proto
  internal/wrappers/grpcs/protos/vorpal/managements/management_grpc.pb.go
  internal/wrappers/grpcs/protos/vorpal/scans/scan.pb.go
  internal/wrappers/grpcs/protos/vorpal/scans/scan.proto
  internal/wrappers/grpcs/protos/vorpal/scans/scan_grpc.pb.go
  internal/wrappers/grpcs/vorpal-grpc.go
  internal/wrappers/grpcs/vorpal.go
  test/integration/result_test.go
Labels: feature

#754 Do not use access token when downloading PDF report and Minio is disabled (AST-44042)
  internal/commands/result.go
  internal/wrappers/results-pdf-http.go
  internal/wrappers/results-pdf.go
Labels: feature

#742 AST-42345 inner tool to install an executable from a zip file (SCAResolver and Vorpal tools)
  internal/commands/scarealtime/sca-linux.go
  internal/commands/scarealtime/sca-mac.go
  internal/commands/scarealtime/sca-realtime-structs.go
  internal/commands/scarealtime/sca-realtime-utils.go
  internal/commands/scarealtime/sca-realtime.go
  internal/commands/scarealtime/sca-realtime_test.go
  internal/commands/scarealtime/scaconfig/sca-linux.go
  internal/commands/scarealtime/scaconfig/sca-mac.go
  internal/commands/scarealtime/scaconfig/sca-windows.go
  internal/commands/vorpal/vorpal_test.go
  internal/commands/vorpal/vorpalconfig/vorpal-linux.go
  internal/commands/vorpal/vorpalconfig/vorpal-mac.go
  internal/commands/vorpal/vorpalconfig/vorpal-windows.go
  internal/services/osinstaller/linux-mac-utils.go
  internal/services/osinstaller/os-installer-structs.go
  internal/services/osinstaller/os-installer.go
  internal/services/osinstaller/windows-utils.go
  test/integration/scan_test.go
Labels: feature

#741 Add Get api call to specific FeatureFlag and use it in the CLI (AST-43188)
  internal/commands/groups.go
  internal/commands/project.go
  internal/commands/result.go
  internal/commands/root.go
  internal/commands/scan.go
  internal/commands/util/import.go
  internal/commands/util/import_test.go
  internal/commands/util/utils.go
  internal/commands/util/utils_test.go
  internal/services/groups.go
  internal/services/groups_test.go
  internal/services/projects.go
  internal/services/projects_test.go
  internal/wrappers/feature-flags-http.go
  internal/wrappers/feature-flags.go
  internal/wrappers/jwt-helper.go
  internal/wrappers/mock/feature-flags-mock.go
  internal/wrappers/mock/jwt-helper-mock.go
  internal/wrappers/mock/uploads-mock.go
  internal/wrappers/uploads-http.go
  internal/wrappers/uploads.go
  test/integration/feature-flags_test.go
  test/integration/import_test.go
Labels: feature

#746 Added new lightweight scan subcommand (AST-38522)
  .gitguardian.yml
  internal/commands/.scripts/up.sh
  internal/commands/data/csharp-no-vul.cs
  internal/commands/data/python-vul-file.py
  internal/commands/root.go
  internal/commands/scan.go
  internal/commands/vorpal-engine.go
  internal/commands/vorpal-engine_test.go
  internal/constants/errors/errors.go
  internal/params/flags.go
  test/integration/data/csharp-no-vul.cs
  test/integration/data/python-vul-file.py
  test/integration/vorpal-engine_test.go
Labels: feature

#760 Bug Fix SCA scan results not available
  internal/params/filters.go
Labels: bug

#737 CLI | Add parallel GetSastMetadetaByID functionality (AST-40381)
  go.mod
  go.sum
  internal/commands/scan.go
  internal/services/sast-metadata.go
  internal/services/sast-metadata_test.go
  internal/wrappers/mock/sast-metadata-mock.go
  internal/wrappers/sast-metadata-http.go
  test/integration/scan_test.go
Labels: bug

#780 CLI | Change get tenant functionality in group wrapper (AST-31008)
  internal/wrappers/groups-http.go
  internal/wrappers/jwt-helper.go
  internal/wrappers/mock/jwt-helper-mock.go
Labels: bug

#767 CLI | Add Vorpal Engine Logic (AST-38523)
  .golangci.yml
  go.mod
  go.sum
  internal/commands/scan.go
  internal/commands/vorpal-engine.go
  internal/commands/vorpal/vorpal-engine.go
  internal/commands/vorpal/vorpal-engine_test.go
  internal/commands/vorpal/vorpal_test.go
  internal/constants/errors/errors.go
  internal/params/binds.go
  internal/params/envs.go
  internal/params/flags.go
  internal/params/keys.go
  internal/services/osinstaller/linux-mac-utils.go
  internal/services/osinstaller/os-installer.go
  internal/services/osinstaller/windows-utils.go
  internal/services/vorpal.go
  internal/services/vorpal_test.go
  internal/wrappers/grpcs/vorpal-grpc.go
  internal/wrappers/grpcs/vorpal.go
  internal/wrappers/jwt-helper.go
  internal/wrappers/mock/jwt-helper-mock.go
  internal/wrappers/mock/vorpal-mock.go
  test/integration/vorpal-engine_test.go
Labels: feature

#786 CLI | Add check to symbolicLink value (AST-45529)
  internal/commands/scan.go
  internal/commands/util/utils.go
  test/integration/data/project-with-directory-symlink/check/originalFolder.html/csharp-no-vul.cs
  test/integration/data/project-with-directory-symlink/originalFolder.html
  test/integration/scan_test.go
Labels: bug, fix
