Repository Checkmarx/ast-cli, pull requests merged in 2024-11, with the labels that each got.

#921 Add Code Repository Flag & Support PR Decoration For GH/GL On-prem (AST-72979, AST-72975)
  .github/workflows/pr-linter.yml
  Dockerfile
  go.mod
  go.sum
  internal/commands/util/pr.go
  internal/commands/util/pr_test.go
  internal/params/flags.go
  internal/wrappers/pr.go
  test/integration/pr_test.go
Labels: feature

#927 Refactor PR Test To Run With A Completed Scan (AST-73348)
  test/integration/pr_test.go
Labels: bug

#916 Added support for rs files. (AST-68753)
  internal/commands/scan_test.go
  internal/params/filters.go
Labels: feature

#929 Log Tmp Zip File Path(AST-40077)
  Dockerfile
  internal/commands/scan.go
  internal/wrappers/client.go
Labels: bug

#924 Deleting a copy file of sca.json when scan runnig with ScaResolver (AST-48074)
  internal/commands/scan.go
  internal/commands/scan_test.go
Labels: bug

#943 Fix gonMac.hcl (AST-0000)
  gonMac.hcl
Labels: bug, fix

#932 Project Creation Flow With AM Phase-2 (AST-72966)
  internal/commands/groups.go
  internal/commands/project.go
  internal/services/groups.go
  internal/services/groups_test.go
  internal/services/projects.go
Labels: feature

#942 Add Pr-Decoration Support On ADO (AST-70135)
  .github/workflows/ci.yml
  .github/workflows/manual-integration-test.yml
  cmd/main.go
  internal/commands/util/pr.go
  internal/commands/util/pr_test.go
  internal/params/binds.go
  internal/params/envs.go
  internal/params/flags.go
  internal/params/keys.go
  internal/wrappers/mock/pr-mock.go
  internal/wrappers/pr-http.go
  internal/wrappers/pr.go
  test/integration/pr_test.go
  test/integration/util_command.go
Labels: feature

#939 Support PR Decoration For BB On-cloud and On-prem(AST-70121)
  .github/workflows/ci.yml
  .github/workflows/manual-integration-test.yml
  cmd/main.go
  internal/commands/util/pr.go
  internal/commands/util/pr_test.go
  internal/params/binds.go
  internal/params/envs.go
  internal/params/flags.go
  internal/params/keys.go
  internal/wrappers/mock/pr-mock.go
  internal/wrappers/pr-http.go
  internal/wrappers/pr.go
  test/integration/pr_test.go
  test/integration/util_command.go
Labels: feature

#946 Fix ASCA Port Overwrite Issue in .checkmarx.yml (AST-75444)
  .github/workflows/ci.yml
  .golangci.yml
  go.mod
  go.sum
  internal/commands/util/configuration_test.go
  internal/services/asca.go
  internal/wrappers/configuration/configuration.go
Labels: bug
