Repository Checkmarx/ast-cli, pull requests merged in 2024-05, with the labels that each got.

#718 Add Makefile
  Makefile
  README.md
Labels: feature

#724 Update The Release to work with VM for Docker - AST-42234
  .github/workflows/release.yml
Labels: bug, docker

#723 Fix project association polling issue (AST-40286)
  internal/commands/.scripts/integration_up.sh
  internal/commands/.scripts/up.sh
  internal/commands/scan.go
  internal/wrappers/client.go
  internal/wrappers/mock/application-mock.go
Labels: bug

#700 Add new exit-code subcommand (AST-37832)
  go.mod
  go.sum
  internal/commands/result.go
  internal/commands/result_test.go
  internal/commands/scan.go
  internal/commands/scan_test.go
  internal/commands/util/learnmore.go
  internal/commands/util/printer/printer.go
  internal/errors/application-errors.go
  internal/errors/exit-codes/exit-codes.go
  internal/wrappers/mock/projects-mock.go
  internal/wrappers/mock/results-mock.go
  internal/wrappers/mock/sca-realtime-mock.go
  internal/wrappers/mock/scans-mock.go
  internal/wrappers/results-http.go
  internal/wrappers/results.go
  test/integration/learnmore_test.go
  test/integration/result_test.go
  test/integration/scan_test.go
  test/integration/tenant_test.go
Labels: feature

#728 CLI | Initialize glSast.Vulnerabilities slice (AST-39033)
  internal/commands/result.go
  internal/commands/result_test.go
  internal/wrappers/mock/results-mock.go
Labels: bug

#674 Add the ability to import a SARIF file (AST-36884, AST-36890)
  .golangci.yml
  cmd/main.go
  go.mod
  internal/commands/.scripts/integration_up.sh
  internal/commands/groups.go
  internal/commands/project.go
  internal/commands/project_test.go
  internal/commands/result.go
  internal/commands/result_test.go
  internal/commands/root.go
  internal/commands/root_test.go
  internal/commands/scan.go
  internal/commands/scan_test.go
  internal/commands/util/completion.go
  internal/commands/util/import.go
  internal/commands/util/import_test.go
  internal/commands/util/utils.go
  internal/commands/util/utils_test.go
  internal/constants/errors/errors.go
  internal/constants/exit-codes/exit-codes.go
  internal/constants/feature-flags/feature-flags.go
  internal/constants/file-extensions.go
  internal/errors/application-errors.go
  internal/params/binds.go
  internal/params/envs.go
  internal/params/flags.go
  internal/params/keys.go
  internal/services/applications.go
  internal/services/applications_test.go
  internal/services/groups.go
  internal/services/groups_test.go
  internal/services/projects.go
  internal/services/projects_test.go
  internal/services/tags.go
  internal/services/tags_test.go
  internal/wrappers/application-http.go
  internal/wrappers/byor-http.go
  internal/wrappers/byor.go
  internal/wrappers/client.go
  internal/wrappers/feature-flags.go
  internal/wrappers/mock/application-mock.go
  internal/wrappers/mock/byor-mock.go
  internal/wrappers/mock/constants.go
  internal/wrappers/mock/groups-mock.go
  internal/wrappers/mock/projects-mock.go
  internal/wrappers/projects-http.go
  internal/wrappers/projects.go
  internal/wrappers/uploads-http.go
  test/integration/data/malformed-sarif.sarif
  test/integration/data/sarif-missing-version.sarif
  test/integration/data/sarif.sarif
  test/integration/data/sarif.zip
  test/integration/data/ssh-key-file.txt
  test/integration/import_test.go
  test/integration/project_test.go
  test/integration/result_test.go
  test/integration/scan_test.go
  test/integration/util_command.go
Labels: feature

#734 Dont Call SCA for Threshold AST-42820
  go.mod
  internal/commands/result.go
  internal/commands/scan.go
  internal/commands/scan_test.go
  internal/wrappers/results-http.go
  test/integration/root_test.go
Labels: bug, fix

#735 Fix FeatureFlag Service Null Error- return the http error to the feature flags service
  internal/wrappers/feature-flags-http.go
Labels: bug, fix

#739 check
  internal/commands/root.go
  internal/wrappers/feature-flags.go
Labels: bug

#745 Fix SCA Threshold Issue AST-43852
  internal/commands/result.go
  internal/commands/scan.go
  internal/commands/util/pr.go
  test/integration/scan_test.go
Labels: bug

#749 AST-42743 Update results-pdf timeout to 7 minutes
  internal/wrappers/results-pdf-http.go
  test/integration/scan_test.go
Labels: bug, fix

#750 Show response to console also in case of partial scan (AST-44163)
  internal/commands/result.go
  internal/commands/result_test.go
Labels: feature
