Repository Checkmarx/ast-cli, pull requests merged in 2024-03, with the labels that each got.

#668 hide chat command from help
  .github/workflows/ci.yml
  go.mod
  go.sum
  internal/commands/chat-kics.go
  internal/commands/chat-sast.go
  internal/commands/chat.go
  internal/commands/util/help.go
Labels: feature

#669 Update Get Application by Name with Exact Match and Update Permissions Log Message (AST-36823)
  internal/commands/project.go
  internal/commands/project_test.go
  internal/commands/scan.go
  internal/commands/scan_test.go
  internal/errors/application-errors.go
  internal/wrappers/application-http.go
  internal/wrappers/mock/application-mock.go
  test/integration/project_test.go
  test/integration/scan_test.go
Labels: bug, fix

#671 AST-36690 | cleanup integration test
  internal/commands/project.go
  test/integration/project_test.go
  test/integration/scan_test.go
Labels: bug, fix

#676 Update Confidence Description (AST-37132)
  go.mod
  internal/commands/sast-prompt.go
  internal/commands/sast-prompt_test.go
Labels: bug, fix

#682 Fix "About this vulnerability" link (AST-35994)
  internal/commands/result.go
  internal/commands/result_test.go
Labels: bug
