Repository Checkmarx/ast-cli, pull requests merged in 2025-01, with the labels that each got.

#978 Disable triggering scorecard scan for hosts other than https github (AST-78326)
  internal/commands/scan.go
  internal/commands/scan_test.go
Labels: feature

#959 Use a new containers-resolver (AST-74985)
  go.mod
  go.sum
  internal/wrappers/container-resolver.go
Labels: feature

#993 Fix the GitHub Cloud URL pattern to account for additional supported repository URLs.
  internal/commands/scan.go
  internal/commands/scan_test.go
Labels: bug, fix

#1013 CLI | Change Rule ID in Sarif files (AST-77145)
  internal/commands/result.go
Labels: bug, fix

#1012 CLI | Fix fast scan and incremental scan initialization in SAST configuration (AST-79107, AST-80586, AST-80553)
  Dockerfile
  internal/commands/scan.go
  internal/commands/scan_test.go
  internal/wrappers/export-http.go
Labels: bug, fix

#1007 Error message for SCS and Enterprise Secret (AST-73370)
  .github/workflows/ai-code-review.yml
  internal/commands/scan.go
  internal/commands/scan_test.go
  internal/wrappers/mock/jwt-helper-mock.go
Labels: bug
