Repository Checkmarx/ast-cli, pull requests merged in 2025-03, with the labels that each got.

#1058 Add origin to all outbound calls (AST-000)
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  .github/workflows/release.yml
  internal/commands/root.go
  internal/params/binds.go
  internal/params/envs.go
  internal/params/flags.go
  internal/params/keys.go
  internal/wrappers/client.go
  internal/wrappers/client_test.go
  test/integration/scan_test.go
Labels: feature

#1064 Add critical severity to kics realtime allowed exit codes (AST-000)
  internal/commands/scan.go
Labels: feature

#1068 Update project creation flow with AM Phase 2 (AST-80248)
  internal/commands/project.go
  internal/constants/feature-flags/feature-flags.go
  internal/services/groups.go
  internal/services/projects.go
  internal/wrappers/access-management-http.go
  internal/wrappers/access-management.go
  internal/wrappers/mock/access-management-mock.go
Labels: bug, fix

#1062 Add Risk Management command. (AST-82718)
  cmd/main.go
  internal/commands/result.go
  internal/commands/result_test.go
  internal/commands/root.go
  internal/commands/root_test.go
  internal/params/binds.go
  internal/params/envs.go
  internal/params/flags.go
  internal/params/keys.go
  internal/wrappers/mock/risk-management-mock.go
  internal/wrappers/risk-management-http.go
  internal/wrappers/risk-management.go
  internal/wrappers/utils/utils.go
  internal/wrappers/utils/utils_test.go
  test/integration/result_test.go
  test/integration/util_command.go
Labels: feature

#1067 Add --iac-security-preset-id flag support (AST-80207)
  internal/commands/.scripts/up.sh
  internal/commands/scan.go
  internal/commands/scan_test.go
  internal/params/flags.go
  internal/wrappers/scans.go
  test/integration/data/iac-insecure.zip
  test/integration/scan_test.go
Labels: feature

#1069 Fix panic exit when containers ff could not be fetched (AST-86767)
  internal/commands/root_test.go
  internal/commands/scan.go
  internal/commands/scan_test.go
  internal/wrappers/mock/feature-flags-mock.go
Labels: bug

#1082 Remove-profile-flag-becuase-lack-support (AST-87103)
  internal/commands/root.go
  internal/commands/util/usercount/user-count.go
  internal/params/flags.go
  test/integration/pr_test.go
Labels: bug
