Repository Checkmarx/ast-cli, pull requests merged in 2025-06, with the labels that each got.

#1152 Fix SCS error message when no Scorecard flags are set (AST-93338)
  internal/commands/scan.go
  internal/commands/scan_test.go
  test/integration/scan_test.go
Labels: bug

#1163 Add support for new Sonar report (AST-36379)
  Dockerfile
  go.mod
  go.sum
  internal/commands/result.go
  internal/commands/result_test.go
  internal/wrappers/results-sonar.go
  test/integration/data/manifests/package.json
Labels: feature

#1166 Remove shlex.Split() parsing of scaResolverParams (AST-96181)
  go.mod
  internal/commands/scan.go
Labels: bug

#1173 Enahance errors in oss realtime (AST-99446)
  internal/commands/oss-realtime-engine.go
  internal/constants/errors/errors.go
  internal/services/ossrealtime/oss-realtime.go
  test/integration/data/manifests/no_dep_packageJson/package.json
  test/integration/oss-realtime_test.go
Labels: bug, fix

#1150 Added new flags Recommended Exclusions and Light Queries for SAST scanner (AST-85153)
  internal/commands/pre_commit.go
  internal/commands/predicates.go
  internal/commands/project.go
  internal/commands/result.go
  internal/commands/root.go
  internal/commands/scan.go
  internal/commands/scan_test.go
  internal/commands/scarealtime/sca-realtime.go
  internal/commands/util/import.go
  internal/commands/util/usercount/azure.go
  internal/commands/util/usercount/bitbucket.go
  internal/commands/util/usercount/bitbucketserver/bitbucket-server.go
  internal/commands/util/usercount/github.go
  internal/commands/util/usercount/gitlab.go
  internal/commands/util/usercount/user-count.go
  internal/commands/util/utils.go
  internal/params/flags.go
  internal/wrappers/scans.go
  test/integration/scan_test.go
Labels: feature

#1167 Add config-file-path flag (AST-97277)
  internal/commands/root.go
  internal/params/flags.go
  internal/wrappers/configuration/configuration.go
  test/integration/configuration_test.go
Labels: feature

#1188 update manifest-parser
  go.mod
  go.sum
Labels: bug, fix

#1192 Fix found vulnerabilities on trivy
  Dockerfile
  go.mod
  go.sum
Labels: bug, fix

#1190 Scan Create command: Fix for Source zip with ScaResolver issue (AST-73409)
  internal/commands/scan.go
  internal/commands/scan_test.go
  test/integration/scan_test.go
Labels: bug, fix

#1194 AddedDirectoryBuildPropsPackageManager (AST-99980)
  internal/params/filters.go
Labels: bug
