Repository Checkmarx/ast-cli, pull requests merged in 2025-07, with the labels that each got.

#1205 Bug/sca-prarams-bug (AST-100708)
  go.mod
  go.sum
  internal/commands/scan.go
  internal/commands/scan_test.go
Labels: bug

#1201 Fix bug number (AST-101835)
  internal/wrappers/results-summary.go
Labels: bug

#1219 Add Telemetry Command (AST-103479)
  cmd/main.go
  go.mod
  go.sum
  internal/commands/root.go
  internal/commands/root_test.go
  internal/commands/telemetry.go
  internal/commands/telemetry_test.go
  internal/params/flags.go
  internal/wrappers/mock/telemetry-mock.go
  internal/wrappers/telemetry-http.go
  internal/wrappers/telemetry.go
  test/integration/telemetry_test.go
  test/integration/util_command.go
Labels: feature

#1236 Added bicep and bicepparam file extension(AST-104436)
  internal/params/filters.go
  internal/wrappers/ntlm/proxy-ntml.go
Labels: bug

#1239 Filter out generic API key vulnerabilities in real-time scan results (AST-106731)
  internal/services/realtimeengine/secretsrealtime/secrets-realtime.go
  internal/services/realtimeengine/secretsrealtime/secrets-realtime_test.go
Labels: bug, fix

#1228 Containers custom images delete and path fixed and version upgrade (AST-105294)
  go.mod
  go.sum
  internal/commands/scan.go
  internal/commands/scan_test.go
Labels: bug

#1247 Fix Duplicate Secret Realtime Results In MultiLine (AST-0000)
  internal/services/realtimeengine/secretsrealtime/config.go
  internal/services/realtimeengine/secretsrealtime/secrets-realtime.go
  internal/services/realtimeengine/secretsrealtime/secrets-realtime_test.go
Labels: bug, fix

#1238 Add IaC Realtime scanning functionality (AST-102217, AST-102218)
  internal/commands/iac-realtime-engine.go
  internal/commands/scan.go
  internal/commands/util/remediation.go
  internal/services/realtimeengine/iacrealtime/config.go
  internal/services/realtimeengine/iacrealtime/constants.go
  internal/services/realtimeengine/iacrealtime/container-manager.go
  internal/services/realtimeengine/iacrealtime/container-manager_test.go
  internal/services/realtimeengine/iacrealtime/file_handler.go
  internal/services/realtimeengine/iacrealtime/file_handler_test.go
  internal/services/realtimeengine/iacrealtime/iac-realtime.go
  internal/services/realtimeengine/iacrealtime/iac-realtime_test.go
  internal/services/realtimeengine/iacrealtime/line_parser.go
  internal/services/realtimeengine/iacrealtime/line_parser_test.go
  internal/services/realtimeengine/iacrealtime/mapper.go
  internal/services/realtimeengine/iacrealtime/mapper_test.go
  internal/services/realtimeengine/iacrealtime/scanner.go
  internal/services/realtimeengine/iacrealtime/scanner_test.go
  test/integration/iac-realtime_test.go
Labels: feature

#1252 Added gemfile support for scan (AST-106740)
  internal/params/filters.go
Labels: bug

#1146 Pre receive feature command (AST-89345)
  .github/workflows/ci.yml
  .golangci.yml
  go.mod
  go.sum
  internal/commands/hooks.go
  internal/commands/pre-receive.go
  internal/commands/pre_commit.go
  internal/commands/pre_receive_test.go
  internal/wrappers/mock/jwt-helper-mock.go
  test/integration/data/pre-receive-data/excludeFile.yaml
  test/integration/data/pre-receive-data/excludeFolder.yaml
  test/integration/data/pre-receive-data/ignoreResultId.yaml
  test/integration/data/pre-receive-data/ignoreRuleId.yaml
  test/integration/pre-receive_test.go
Labels: feature
