Repository Checkmarx/ast-cli, pull requests merged in 2025-02, with the labels that each got.

#1023 CLI | Container Security filter flags (AST-82260)
  internal/commands/scan.go
  internal/params/flags.go
  internal/wrappers/scans.go
  test/integration/scan_test.go
Labels: feature

#1025 Add retry mechanism to 502 response (AST-82566)
  internal/wrappers/client.go
  internal/wrappers/client_test.go
  internal/wrappers/constants.go
  internal/wrappers/projects-http.go
  internal/wrappers/scans-http.go
  internal/wrappers/wrapper-constants.go
Labels: feature

#1028 Fix containers resolver temp folder cleanup (AST-82733)
  go.mod
  go.sum
Labels: bug

#1033 Skip of policy evaluated when the scan not finished(AST-81796)
  internal/commands/result.go
  test/integration/scan_test.go
Labels: feature

#1040 Add a new field State ID to Triage Show command (AST-81675)
  internal/commands/predicates.go
  internal/wrappers/predicates.go
Labels: feature

#1046 Change State ID to int(AST-81675)
  internal/commands/predicates.go
  internal/wrappers/predicates.go
Labels: feature

#1045 Make writeCredentialsToCache func thread safe (AST-82856)
  Dockerfile
  internal/wrappers/client.go
  internal/wrappers/client_test.go
Labels: bug, fix

#1039 Triage update support custom state.(AST-81674)
  internal/commands/predicates.go
  internal/commands/predicates_test.go
  internal/params/flags.go
  internal/wrappers/feature-flags.go
  internal/wrappers/mock/custom-states-mock.go
  internal/wrappers/predicates-http.go
  internal/wrappers/predicates.go
Labels: feature

#1035 Remove 'not yet supported' from container image flags (AST-81120)
  .github/workflows/pr-automation.yml
  internal/commands/scan.go
Labels: bug, fix

#1051 Fix sonar column start position (AST-65811)
  .github/workflows/ci.yml
  internal/commands/result.go
Labels: bug

#1022 Add SSCS as scan type for the triage command (AST-72075)
  internal/commands/predicates.go
  internal/commands/util/configuration_test.go
  internal/params/binds.go
  internal/params/envs.go
  internal/params/keys.go
  internal/wrappers/configuration/configuration.go
  internal/wrappers/predicates-http.go
  internal/wrappers/scan-overview-http.go
Labels: feature

#1053 Extract client_id dynamically from token (AST-84586)
  internal/wrappers/client.go
  internal/wrappers/client_test.go
Labels: feature
